### ISSUE TITLE
Long Term Support plan?

### ISSUE THREAD

**Issue by ceedriic** [twbs/release#6]
I've read your "Introducing our Long Term Support plan" blog aimed at "strengthening the stability [...] of releases".
The title look good but after reading the blog, it seem to me that a less Orwellian title would be "Reducing the support of releases from 5 years to 1 year" (with LTS included)
or "Reducing the support of releases from 15 months to 1 month" (without LTS included)
 
I'm filing this has a documentation bug to fix the title the blog, because I believe it is misleading. The second misleading thing in this post is the labelling of "development work" as "current" in the plots. If I read your graphic correctly, the plan is to have no overlap in the future between supported, released versions. If I read your graphic correctly and by any chance 5.0 is released later than planned, there might be no stable version at all as of February 2020.

I've no right to complain, this is free software, but this is still concerning.

**Comment by bardiharborow** [comment]
I'm not sure what you mean by Orwellian in this context, but I'll address what I can. We're very open to feedback – the whole premise of this initiative is there have been problems in the past and we are trying to learn from them.

> The second misleading thing in this post is the labelling of "development work" as "current" in the plots.

"Current" for me means that a X.0 version has been released. When an LTS branch is cut from master ("Active LTS Start"), that's when we'd start landing PRs on X+1.

> If I read your graphic correctly and by any chance 5.0 is released later than planned, there might be no stable version at all as of February 2020.

If you've followed Bootstrap for many years, you'll know we have landed in similar situations in the past. Moving forward, support periods advised are minimums, so for example a late 5.0 would likely mean an extension of v4 LTS maintenance. With the launch of this "LTS plan", we're backporting changes at a much higher rate than previously, and beginning to gain experience supporting multiple versions at once.

This will be somewhat of a journey, and we made a oversight already that'll require us to release an unplanned 4.4 (originally the blog post backdated v4 LTS start to the 4.3 release date), but we are committed to getting this right. I'll soon be pushing for regular working group approval of schedules, so that everyone can be on the same page. If there's anything I can do to clear things up further, let me know.
